# Generated by Django 4.0.4 on 2022-08-03 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 3, 16, 26, 10, 855848, tzinfo=utc)),
        ),
    ]
