# Generated by Django 4.0.4 on 2022-08-05 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_comment_date_posted_alter_auction_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Books', 'Book'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Sports', 'Sports')], max_length=10),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 51, 45, 634639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 51, 45, 635637, tzinfo=utc)),
        ),
    ]
