# Generated by Django 4.0.4 on 2022-08-06 07:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_category_alter_auction_date_posted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.CharField(choices=[('None', 'None'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Furniture', 'Furniture'), ('Toys', 'Toys'), ('Sports', 'Sports')], default=(), max_length=255),
        ),
        migrations.AlterField(
            model_name='auction',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 7, 25, 13, 692034, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 6, 7, 25, 13, 693034, tzinfo=utc)),
        ),
    ]
